inherit_gem:
  salsify_rubocop: conf/rubocop.yml

AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - 'vendor/**/*'
    - 'gemfiles/**/*'

Naming/FileName:
  Exclude:
    - Appraisals
    - lib/active_record-forbid_implicit_connection_checkout.rb
