language: ruby
gemfile:
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_6.0.gemfile
rvm:
  - 2.5.1
  - 2.6.3
services:
  - postgresql
before_install: gem install bundler -v 1.12.4
script:
  - bundle exec rubocop
  - bundle exec rspec
