require 'active_record'
require 'active_record/forbid_implicit_connection_checkout/version'
require 'active_record/implicit_connection_forbidden_error'

require 'forbid_implicit_connection_checkout_for_thread'
require 'active_record_connection_override'

ActiveRecord::Base.include(ForbidImplicitConnectionCheckoutForThread)
ActiveRecord::Base.singleton_class.prepend(ActiveRecordConnectionOverride)
